### ISSUE TITLE
Crash / 500 error when removing traits from variants

### ISSUE THREAD

**Issue by Provinite** [Provinite/clovercoin-app#41]
```{
  "operationName": "deleteTraitListEntry",
  "variables": {
    "id": "c5e48664-f2e9-4857-94cd-c237902d4189"
  },
  "query": "mutation deleteTraitListEntry($id: ID!) {\n  deleteTraitListEntry(id: $id) {\n    __typename\n    ... on DeleteResponse {\n      ok\n      __typename\n    }\n    ... on InvalidArgumentError {\n      ...InvalidArgumentErrorFragment\n      __typename\n    }\n    ... on BaseError {\n      ...BaseErrorFragment\n      __typename\n    }\n  }\n}\n\nfragment InvalidArgumentErrorFragment on InvalidArgumentError {\n  message\n  validationErrors {\n    constraints {\n      key\n      description\n      __typename\n    }\n    field\n    __typename\n  }\n  __typename\n}\n\nfragment BaseErrorFragment on BaseError {\n  message\n  __typename\n}"
}```


https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fbeta-cc-api-fn/log-events/2023$252F08$252F10$252F$255B$2524LATEST$255Db396dc802a9d47a39ed538c24fb368bc

**Comment by Provinite** [comment]
```<html>
<body>
<!--StartFragment-->

2023-08-10T12:02:44.388-05:00 | dataType: undefined,
-- | --
  | 2023-08-10T12:02:44.388-05:00 | constraint: undefined,
  | 2023-08-10T12:02:44.388-05:00 | file: 'arrayfuncs.c',
  | 2023-08-10T12:02:44.388-05:00 | line: '272',
  | 2023-08-10T12:02:44.388-05:00 | routine: 'array_in',
  | 2023-08-10T12:02:44.388-05:00 | level: 'error',
  | 2023-08-10T12:02:44.388-05:00 | stack: 'QueryFailedError: malformed array literal: "[]"\n' +
  | 2023-08-10T12:02:44.388-05:00 | ' at oGe.query (/var/node_modules/typeorm/src/driver/postgres/PostgresQueryRunner.ts:299:19)\n' +
  | 2023-08-10T12:02:44.388-05:00 | ' at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
  | 2023-08-10T12:02:44.388-05:00 | ' at o7e.execute (/var/node_modules/src/query-builder/InsertQueryBuilder.ts:163:33)\n' +
  | 2023-08-10T12:02:44.388-05:00 | ' at M$e.executeInsertOperations (/var/node_modules/src/persistence/SubjectExecutor.ts:434:42)\n' +
  | 2023-08-10T12:02:44.388-05:00 | ' at M$e.execute (/var/node_modules/src/persistence/SubjectExecutor.ts:137:9)\n' +
  | 2023-08-10T12:02:44.388-05:00 | ' at $e.execute (/var/node_modules/src/persistence/EntityPersistExecutor.ts:182:21)\n' +
  | 2023-08-10T12:02:44.388-05:00 | ' at Soe.create (/var/src/business/EntityController.ts:28:15)\n' +
  | 2023-08-10T12:02:44.388-05:00 | ' at dispatchHandler (/var/node_modules/type-graphql/dist/resolvers/helpers.js:82:24)\n' +
  | 2023-08-10T12:02:44.388-05:00 | ' at <anonymous> (/var/node_modules/type-graphql/dist/resolvers/helpers.js:83:26)\n' +
  | 2023-08-10T12:02:44.388-05:00 | ' at loggingMiddleware (/var/src/server.ts:201:3)',
  | 2023-08-10T12:02:44.388-05:00 | message: 'malformed array literal: "[]"',
  | 2023-08-10T12:02:44.388-05:00 | timestamp: '2023-08-10T17:02:42.248Z'
  | 2023-08-10T12:02:44.388-05:00 | }

<!--EndFragment-->
</body>
</html>```
